msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-22 19:19+0200\n"
"PO-Revision-Date: \n"
"Last-Translator: Andrej Tobola <andrej.tobola@gmail.com>\n"
"Language-Team: \n"
"Language: sk\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-SourceCharset: utf-8\n"
"X-Generator: Poedit 2.4.2\n"

#: ../plugin.py:441
msgid ""
"\n"
"The found files:"
msgstr ""
"\n"
"Nájdené súbory:"

#: ../plugin.py:358
msgid ""
"\n"
"You are using dual multiboot!"
msgstr ""
"\n"
"Používate duálny multiboot!"

#: ../plugin.py:447
#, python-format
msgid "  %s (maybe error)"
msgstr "  %s (možno chyba)"

#: ../plugin.py:444
#, python-format
msgid "  %s (maybe ok)"
msgstr "  %s (možno ok)"

#: ../message.py:180
msgid " MB available space"
msgstr " MB volného miesta"

#: ../message.py:185
msgid " MB needed space"
msgstr " MB potrebného miesta"

#: ../plugin.py:450
msgid " nothing!"
msgstr " nič!"

#: ../message.py:45
msgid " size to be backed up: "
msgstr " zálohovaná veľkosť: "

#: ../message.py:175
msgid " to make a back-up!"
msgstr " pre vytvorenie zálohy!"

#: ../message.py:169
msgid "* * * WARNING * * *"
msgstr "* * * Varovanie * * *"

#: ../plugin.py:480
msgid "A recording is currently running. Please stop the recording before trying to start a flashing."
msgstr "V súčasnej dobe prebieha nahrávanie. Pred pokusom o spustenie obnovy prosím zastavte nahrávanie."

#: ../message.py:70
msgid "Additional backup -> "
msgstr "Ďalšia záloha -> "

#: ../message.py:35
msgid "BACK-UP TOOL, FOR MAKING A COMPLETE BACK-UP"
msgstr "BACK-UP nástroj na výrobu kompletnej zálohy operačného systému"

#: ../plugin.py:132
msgid "Backup > HDD"
msgstr "Záloha > HDD"

#: ../plugin.py:130
msgid "Backup > MMC"
msgstr "Záloha > MMC"

#: ../plugin.py:133
msgid "Backup > USB"
msgstr "Záloha > USB"

#: ../plugin.py:584 ../plugin.py:591
msgid "Backup and restore your image"
msgstr "Zálohovať a obnoviť zálohu systému"

#: ../message.py:149
msgid "Backup done with: "
msgstr "Záloha vytvorená: "

#: ../message.py:106
msgid "Backup finished and copied to your USB-flashdrive."
msgstr "Zálohovanie bolo dokončené a skopírované na USB."

#: ../plugin.py:338 ../plugin.py:541
msgid "Backup info"
msgstr "Informácia o zálohe"

#: ../plugin.py:583 ../plugin.py:590
msgid "BackupSuite"
msgstr "BackupSuite"

#: ../plugin.py:131 ../plugin.py:233 ../plugin.py:262
msgid "Close"
msgstr "Zatvoriť"

#: ../message.py:65
msgid "Create: kerneldump"
msgstr "Vytvára sa : kerneldump"

#: ../message.py:60
msgid "Create: root.ubifs"
msgstr "Vytvára sa : root.ubifs"

#: ../plugin.py:339 ../plugin.py:570
msgid "Delete"
msgstr "Vymazať"

#: ../plugin.py:567
msgid "Delete backup"
msgstr "Vymazať zálohu"

#: ../plugin.py:540
#, python-format
msgid "Do you really want to unpack %s ?"
msgstr "Naozaj chcete rozbaliť %s ?"

#: ../plugin.py:153
msgid ""
"Do you want to make a back-up on USB?\n"
"\n"
"This only takes a few minutes depending on the used filesystem and is fully automatic.\n"
"\n"
"Make sure you first insert an USB flash drive before you select Yes."
msgstr ""
"Chcete vytvoriť zálohu na USB?\n"
"\n"
"Dĺžka zálohovania závisí na použitom súborovom systéme, je plne automacitká a trvá iba niekoľko minút.\n"
"\n"
"Uistite sa, že je USB disk zasunutý pred tým, ako stlačíte Áno."

#: ../plugin.py:150
msgid ""
"Do you want to make an USB-back-up image on HDD? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""
"Chcete vytvoriť USB zálohu operačného systému na HDD?\n"
"\n"
"Záloha je plne automatická a trvá iba niekoľko minút.\n"

#: ../plugin.py:156
msgid ""
"Do you want to make an USB-back-up image on MMC? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""
"Chcete vytvoriť USB zálohu operačného systému na pamäťovú kartu?\n"
"\n"
"Záloha je plne automatická a trvá iba niekoľko minút.\n"
"\n"

#: ../plugin.py:470
msgid "Exit"
msgstr "Ukončiť"

#: ../plugin.py:484
msgid "Flashing: "
msgstr "Flashing: "

#: ../plugin.py:369
msgid "For flashing your receiver files are needed:\n"
msgstr "Pre obnovenie sú potrebné súbory:\n"

#: ../message.py:129
msgid "Full back-up direct to USB"
msgstr "Plná záloha priamo na USB"

#: ../plugin.py:194
msgid "Full back-up on HDD"
msgstr "Plná záloha na HDD"

#: ../plugin.py:208
msgid "Full back-up on MMC"
msgstr "Plná záloha na MMC"

#: ../plugin.py:201
msgid "Full back-up to USB"
msgstr "Plná záloha na USB"

#: ../message.py:235
msgid "Full back-up to the MultiMediaCard"
msgstr "Plná záloha na pamäťovú kartu (MMC)"

#: ../message.py:111
msgid "Full back-up to the harddisk"
msgstr "Plná záloha na harddisk"

#: ../message.py:123
msgid "If you place an USB-stick containing this file then the back-up will be automatically made onto the USB-stick and can be used to restore the current image if necessary."
msgstr "Ak zasuniete USB disk obsahujúci tento súbor, záloha bude automaticky vykonaná na tento disk a môže byť neskôr použitá na obnovenie zálohy OS v prípade potreby."

#: ../message.py:90
msgid "Image creation FAILED!"
msgstr "Vytvorenie zálohy OS zlyhalo!"

#: ../message.py:225
msgid "Installed packages contained in this backup:"
msgstr "Inštalované balíky dostupné v tejto zálohe:"

#: ../message.py:154
msgid "KB per second"
msgstr "KB za sekundu"

#: ../plugin.py:127
msgid "Make a backup or restore a backup"
msgstr "Vytvoriť zálohu alebo obnoviť zálohu"

#: ../message.py:159
msgid "Most likely this back-up can't be restored because of it's size, it's simply too big to restore. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr "S najväčšou pravdepodobnosťou sa záloha nedá obnoviť, pretože je príliš velká pre obnovenie. Jedná sa o obmedzenie bootloadera, nie o chybu v zálohe alebo chybu doplnku BackupSuite."

#: ../plugin.py:45
msgid "NAS"
msgstr "NAS"

#: ../message.py:230
msgid "NFI Image created in: "
msgstr "NFI záloha vytvorená v: "

#: ../plugin.py:516
msgid "NOT found files for flashing!\n"
msgstr "Neboli nájdené súbory pre obnovenie zálohy!\n"

#: ../message.py:220
msgid "No additional USB-stick found to copy an extra backup"
msgstr "Na vytvorenie extra zálohy nebol nájdený dodatočný USB disk"

#: ../plugin.py:173 ../message.py:30
msgid "No supported receiver found!"
msgstr "Nebol nájdený žiadny podporovaný prijímač!"

#: ../message.py:170
msgid "Not enough free space on "
msgstr "Nedostatok volného miesta na "

#: ../plugin.py:458 ../plugin.py:499
msgid "Only kernel"
msgstr "Iba kernel"

#: ../plugin.py:457 ../plugin.py:496
msgid "Only root"
msgstr "Iba root"

#: ../message.py:118
msgid "PLEASE READ THIS:"
msgstr "Prosím prečítajte si toto:"

#: ../message.py:40
msgid "Please be patient, a backup will now be made, this will take about: "
msgstr "Buďte prosím trpezlivý, vytvorí sa záloha operačného systému, ktorá potrvá približne: "

#: ../message.py:85
msgid "Please check the manual of the receiver on how to restore the image."
msgstr "Skontrolujte si prosím v príručke prijímača, ako obnoviť zálohu Image."

#: ../plugin.py:234
msgid "Please wait"
msgstr "Prosím čakajte"

#: ../plugin.py:528
msgid "Please: DO NOT reboot your STB and turn off the power.\n"
msgstr "Upozornenie: Nereštartujte STB ani nevypínajte napájanie.\n"

#: ../message.py:215
msgid "Probably you are trying to make the back-up in flash memory"
msgstr "Pravdepodobne sa pokúšate vytvoriť zálohu vo flash pamäti"

#: ../plugin.py:134
msgid "Restore backup"
msgstr "Obnoviť zálohu"

#: ../plugin.py:336 ../plugin.py:353 ../plugin.py:362
msgid "Run flash"
msgstr "Spustiť obnovu"

#: ../plugin.py:464 ../plugin.py:511
msgid "Second partition (only kernel)"
msgstr "Druhá partícia (iba kernel)"

#: ../plugin.py:463 ../plugin.py:508
msgid "Second partition (only root)"
msgstr "Druhá partícia (iba root)"

#: ../plugin.py:462 ../plugin.py:505
msgid "Second partition (root and kernel)"
msgstr "Druhá partícia (root a kernel)"

#: ../plugin.py:368
msgid "Select parameter for start flash!\n"
msgstr "Vyberte parameter pre spustenie obnovy!\n"

#: ../plugin.py:261
msgid "Select the folder with backup"
msgstr "Vyberte zložku so zálohou"

#: ../plugin.py:521
msgid "Show only found image and mtd partitions.\n"
msgstr "Zobraziť iba nájdený Image a MTD oddiely..\n"

#: ../plugin.py:455 ../plugin.py:487
msgid "Simulate (no write)"
msgstr "Simulácia (bez zápisu)"

#: ../plugin.py:461 ../plugin.py:502
msgid "Simulate second partition (no write)"
msgstr "Simulovať druhú partíciu (bez zápisu)"

#: ../message.py:55
msgid "Some information about the task"
msgstr "Informácie o vykonávanej zálohe"

#: ../plugin.py:456 ../plugin.py:490
msgid "Standard (root and kernel)"
msgstr "Štandard (root a kernel)"

#: ../message.py:134
msgid "The content of the folder is:"
msgstr "Obsah zložky je:"

#: ../plugin.py:529
msgid "The image or kernel will be flashing and auto booted in few minutes.\n"
msgstr "Image alebo kernel bude obnovený a prijímač sa automaticky do niekolkých minút reštartuje.\n"

#: ../message.py:190
msgid "The program will abort, please try another medium with more free space to create your back-up."
msgstr "Proces bude prerušený, prosím skúste iné médium s dostatkom volného miesta pre vytvorenie zálohy."

#: ../message.py:124
msgid "The program will exit now."
msgstr "Program bude ukončený."

#: ../message.py:164
msgid "There COULD be a problem with restoring this back-up because the size of the back-up comes close to the maximum size. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr "Mohol by byť problém s obnovením téjto zálohy, pretože veľkosť zálohy sa blíži k maximálnej velkosti. Jedná sa o obmedzenie bootloadera, nie o chybu v zálohe alebo chybu doplnku BackupSuite."

#: ../message.py:116
msgid "There is NO valid USB-stick found, so I've got nothing to do."
msgstr "Nebol nájdený potrebný USB disk, záloha sa nevykoná."

#: ../message.py:100
msgid "There is a valid USB-flashdrive detected in one of the USB-ports, therefore an extra copy of the back-up image will now be copied to that USB-flashdrive."
msgstr "USB nájdený v jednom z USB portov, extra kópia zálohy operačného systému bude preto skopírovana na toto USB."

#: ../message.py:101
msgid "This only takes about 20 seconds....."
msgstr "Potrvá to približne 20 sekúnd ....."

#: ../message.py:139
msgid "Time required for this process: "
msgstr "Čas potrebný pre tento proces: "

#: ../message.py:119
msgid "To back-up directly to the USB-stick, the USB-stick MUST contain a file with the name:"
msgstr "Ak chcete zálohovať priamo na USB disk, tento musí obsahovať súbor s názvom:"

#: ../message.py:75
msgid "USB Image created in: "
msgstr "USB záloha vytvorená v: "

#: ../plugin.py:334 ../plugin.py:537
msgid "Unzip"
msgstr "Rozbaliť"

#: ../message.py:200
msgid "Using your own custom lookuptable.txt from the folder /etc"
msgstr "Použije sa váš vlastný lookuptable.txt zo zložky /etc"

#: ../message.py:205
msgid "Version unknown, probably not installed the right way."
msgstr "Verzia neznáma, pravdepodobne nebola správne nainštalovaná."

#: ../plugin.py:359
msgid ""
"Warning!\n"
"Use at your own risk! Make always a backup before use!\n"
"Don't use it if you use multiple ubi volumes in ubi layer!"
msgstr ""
"Varovanie!\n"
"Používate na vlastné riziko! Odporúčame urobiť zálohu pred každým použitím!\n"
"Nepoužívajte to, ak používate viac Ubi jednotiek v UBI vrstve!"

#: ../plugin.py:232
msgid "What is new since the last release?"
msgstr "Čo je nové od poslednej verzie?"

#: ../plugin.py:571
#, python-format
msgid ""
"You are about to delete this backup:\n"
"\n"
"%s\n"
"Continue?"
msgstr ""
"Chystáte sa odstrániť túto zálohu:\n"
"\n"
"%s\n"
"Pokračovať?"

#: ../plugin.py:527
msgid "Your STB will freeze during the flashing process.\n"
msgstr "Počas procesu obnovy môže Váš STB prestať reagovať.\n"

#: ../message.py:80
msgid "and there is made an extra copy in: "
msgstr "a ďalšia vytvorená kópia v: "

#: ../message.py:95
msgid "available "
msgstr "dostupných "

#: ../message.py:120
msgid "backupstick or"
msgstr "backupstick alebo"

#: ../message.py:121
msgid "backupstick.txt"
msgstr "backupstick.txt"

#: ../plugin.py:266 ../plugin.py:328
#, python-format
msgid "current:  %s"
msgstr "adresár:  %s"

#: ../message.py:195
msgid "is not executable..."
msgstr "nie je spustiteľný..."

#: ../message.py:144
msgid "minutes"
msgstr "minút"

#: ../message.py:50
msgid "not found, the backup process will be aborted!"
msgstr "nebol nájdený, proces zálohovania bude prerušený!"

#: ../message.py:210
msgid "not installed yet, now installing"
msgstr "ešte nie je nainštalované, inštalujem teraz"

#: ../plugin.py:526
msgid "ofgwrite will stop enigma2 now to run the flash.\n"
msgstr "ofgwrite ukončí beh OS Enigma z dôvodu obnovy systému .\n"
